import type { LucideIcon } from "lucide-react";
import {
  ShieldCheck,
  Award,
  Flag,
  Sparkles,
  HeartHandshake,
  Users,
  Factory,
  Wind,
  Leaf,
  Gauge,
  Compass,
  Target,
  Sprout,
  Zap,
  TreePine,
  Recycle,
  HandHeart,
  Sun,
  Boxes,
  Truck,
  Flame,
  Beaker,
  Layers,
  Snowflake,
  Package,
  Droplets,
  FlaskConical,
  Filter,
  Globe2,
  HardHat,
  Landmark,
  FileBadge,
  Newspaper,
  Video,
  CalendarDays,
  Calendar,
  Building2,
  Phone,
  Mail,
  MapPin,
  FileText,
  Play,
  Mic,
  Quote,
  ArrowRight,
  CircleDot,
  ChevronRight,
} from "lucide-react";

/**
 * Maps the kebab-case icon keys editors pick in Sanity (see
 * src/sanity/schemaTypes/shared/iconKey.ts) to lucide-react components.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  "shield-check": ShieldCheck,
  award: Award,
  flag: Flag,
  sparkles: Sparkles,
  "heart-handshake": HeartHandshake,
  users: Users,
  factory: Factory,
  wind: Wind,
  leaf: Leaf,
  gauge: Gauge,
  compass: Compass,
  target: Target,
  sprout: Sprout,
  zap: Zap,
  "tree-pine": TreePine,
  recycle: Recycle,
  "hand-heart": HandHeart,
  sun: Sun,
  boxes: Boxes,
  truck: Truck,
  flame: Flame,
  beaker: Beaker,
  layers: Layers,
  snowflake: Snowflake,
  package: Package,
  droplets: Droplets,
  "flask-conical": FlaskConical,
  filter: Filter,
  "globe-2": Globe2,
  "hard-hat": HardHat,
  landmark: Landmark,
  "file-badge": FileBadge,
  newspaper: Newspaper,
  video: Video,
  "calendar-days": CalendarDays,
  calendar: Calendar,
  "building-2": Building2,
  phone: Phone,
  mail: Mail,
  "map-pin": MapPin,
  "file-text": FileText,
  play: Play,
  mic: Mic,
  quote: Quote,
  "arrow-right": ArrowRight,
  "circle-dot": CircleDot,
  "chevron-right": ChevronRight,
};

/** Resolve an icon key to a component, falling back when missing/unknown. */
export function iconFromKey(
  key: string | null | undefined,
  fallback: LucideIcon,
): LucideIcon {
  return (key && ICON_MAP[key]) || fallback;
}
